### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by freekmurze** [laravel-notification-channels/gitter#1]
Let me know when you're done with the code, tests and readme. I'll do a little code review, register the package on Packagist and start some automatic code quality checks.

**Comment by jhaoda** [comment]
@freekmurze ready!

**Comment by jhaoda** [comment]
@freekmurze ping :smiley:

**Comment by freekmurze** [comment]
Pong! Will take a look soon!

**Comment by freekmurze** [comment]
I changed some things. Most notably I remove the `toArray` method. I believe this method isn't necessary as you can just use the properties from the message in the channel.

If I've done anything you don't like let me know.

The package is now registered on packagist and the code quality services have been set up.
